const predefinedFiles = [
    { name: 'AVARÉ.kmz', url: './cpfl_santacruz/AVARÉ.kmz' },
    { name: 'CACONDE.kmz', url: './cpfl_santacruz/CACONDE.kmz' },
    { name: 'CASA BRANCA.kmz', url: './cpfl_santacruz/CASA BRANCA.kmz' },
    { name: 'CHAVANTES.kmz', url: './cpfl_santacruz/CHAVANTES.kmz' },
    { name: 'ITAPETININGA.kmz', url: './cpfl_santacruz/ITAPETININGA.kmz' },
    { name: 'ITAÍ.kmz', url: './cpfl_santacruz/ITAÍ.kmz' },
    { name: 'JACAREZINHO.kmz', url: './cpfl_santacruz/JACAREZINHO.kmz' },
    { name: 'JAGUARIÚNA.kmz', url: './cpfl_santacruz/JAGUARIÚNA.kmz' },
    { name: 'MOCOCA.kmz', url: './cpfl_santacruz/MOCOCA.kmz' },
    { name: 'MONTE SANTO DE MINAS.kmz', url: './cpfl_santacruz/MONTE SANTO DE MINAS.kmz' },
    { name: 'OURINHOS.kmz', url: './cpfl_santacruz/OURINHOS.kmz' },
    { name: 'PEDREIRA.kmz', url: './cpfl_santacruz/PEDREIRA.kmz' },
    { name: 'PIRAJU.kmz', url: './cpfl_santacruz/PIRAJU.kmz' },
    { name: 'SANTA CRUZ DO RIO PARDO.kmz', url: './cpfl_santacruz/SANTA CRUZ DO RIO PARDO.kmz' },
    { name: 'SÃO JOSÉ DO RIO PARDO.kmz', url: './cpfl_santacruz/SÃO JOSÉ DO RIO PARDO.kmz' },
    { name: 'SÃO PEDRO DO TURVO.kmz', url: './cpfl_santacruz/SÃO PEDRO DO TURVO.kmz' },
    { name: 'TAQUARITUBA.kmz', url: './cpfl_santacruz/TAQUARITUBA.kmz' },
    { name: 'ÁGUAS DE SANTA BÁRBARA.kmz', url: './cpfl_santacruz/ÁGUAS DE SANTA BÁRBARA.kmz' },
];