const predefinedFiles = [
    { name: 'BOITUVA.kmz', url: './cpfl_piratininga/BOITUVA.kmz' },
    { name: 'CAMPO LIMPO.kmz', url: './cpfl_piratininga/CAMPO LIMPO.kmz' },
    { name: 'CAPELA DO ALTO.kmz', url: './cpfl_piratininga/CAPELA DO ALTO.kmz' },
    { name: 'CUBATAO.kmz', url: './cpfl_piratininga/CUBATAO.kmz' },
    { name: 'IBIUNA.kmz', url: './cpfl_piratininga/IBIUNA.kmz' },
    { name: 'INDAIATUBA.kmz', url: './cpfl_piratininga/INDAIATUBA.kmz' },
    { name: 'ITU.kmz', url: './cpfl_piratininga/ITU.kmz' },
    { name: 'JUNDIAI.kmz', url: './cpfl_piratininga/JUNDIAI.kmz' },
    { name: 'LOUVEIRA.kmz', url: './cpfl_piratininga/LOUVEIRA.kmz' },
    { name: 'MAIRINQUE.kmz', url: './cpfl_piratininga/MAIRINQUE.kmz' },
    { name: 'PORTO FELIZ.kmz', url: './cpfl_piratininga/PORTO FELIZ.kmz' },
    { name: 'PRAIA GRANDE.kmz', url: './cpfl_piratininga/PRAIA GRANDE.kmz' },
    { name: 'SALTO DE PIRAPORA.kmz', url: './cpfl_piratininga/SALTO DE PIRAPORA.kmz' },
    { name: 'SALTO.kmz', url: './cpfl_piratininga/SALTO.kmz' },
    { name: 'SANTOS.kmz', url: './cpfl_piratininga/SANTOS.kmz' },
    { name: 'SAO ROQUE.kmz', url: './cpfl_piratininga/SAO ROQUE.kmz' },
    { name: 'SAO VICENTE.kmz', url: './cpfl_piratininga/SAO VICENTE.kmz' },
    { name: 'SOROCABA.kmz', url: './cpfl_piratininga/SOROCABA.kmz' },
    { name: 'VARZEA PAULISTA.kmz', url: './cpfl_piratininga/VARZEA PAULISTA.kmz' },
    { name: 'VICENTE DE CARVALHO.kmz', url: './cpfl_piratininga/VICENTE DE CARVALHO.kmz' },
    { name: 'VINHEDO.kmz', url: './cpfl_piratininga/VINHEDO.kmz' },
    { name: 'VOTORANTIM.kmz', url: './cpfl_piratininga/VOTORANTIM.kmz' },
];