const predefinedFiles = [
    { name: 'AGUAS DE LINDOIA.kmz', url: './cpfl_paulista/AGUAS DE LINDOIA.kmz' },
    { name: 'AGUDOS.kmz', url: './cpfl_paulista/AGUDOS.kmz' },
    { name: 'ALTINOPOLIS.kmz', url: './cpfl_paulista/ALTINOPOLIS.kmz' },
    { name: 'AMERICANA.kmz', url: './cpfl_paulista/AMERICANA.kmz' },
    { name: 'AMPARO.kmz', url: './cpfl_paulista/AMPARO.kmz' },
    { name: 'ARACATUBA.kmz', url: './cpfl_paulista/ARACATUBA.kmz' },
    { name: 'ARARAQUARA.kmz', url: './cpfl_paulista/ARARAQUARA.kmz' },
    { name: 'BARIRI.kmz', url: './cpfl_paulista/BARIRI.kmz' },
    { name: 'BARRA BONITA.kmz', url: './cpfl_paulista/BARRA BONITA.kmz' },
    { name: 'BARRETOS.kmz', url: './cpfl_paulista/BARRETOS.kmz' },
    { name: 'BATATAIS.kmz', url: './cpfl_paulista/BATATAIS.kmz' },
    { name: 'BAURU.kmz', url: './cpfl_paulista/BAURU.kmz' },
    { name: 'BEBEDOURO.kmz', url: './cpfl_paulista/BEBEDOURO.kmz' },
    { name: 'BIRIGUI.kmz', url: './cpfl_paulista/BIRIGUI.kmz' },
    { name: 'BOA ESPERANCA DO SUL.kmz', url: './cpfl_paulista/BOA ESPERANCA DO SUL.kmz' },
    { name: 'BOTUCATU.kmz', url: './cpfl_paulista/BOTUCATU.kmz' },
    { name: 'BRAUNA.kmz', url: './cpfl_paulista/BRAUNA.kmz' },
    { name: 'BROTAS.kmz', url: './cpfl_paulista/BROTAS.kmz' },
    { name: 'CAFELANDIA.kmz', url: './cpfl_paulista/CAFELANDIA.kmz' },
    { name: 'CAJOBI.kmz', url: './cpfl_paulista/CAJOBI.kmz' },
    { name: 'CAJURU.kmz', url: './cpfl_paulista/CAJURU.kmz' },
    { name: 'CAMPINAS BARAO GERALDO.kmz', url: './cpfl_paulista/CAMPINAS BARAO GERALDO.kmz' },
    { name: 'CAMPINAS CAMPO GRANDE.kmz', url: './cpfl_paulista/CAMPINAS CAMPO GRANDE.kmz' },
    { name: 'CAMPINAS CENTRO.kmz', url: './cpfl_paulista/CAMPINAS CENTRO.kmz' },
    { name: 'CAMPINAS SOUZAS.kmz', url: './cpfl_paulista/CAMPINAS SOUZAS.kmz' },
    { name: 'CAMPINAS TREVO.kmz', url: './cpfl_paulista/CAMPINAS TREVO.kmz' },
    { name: 'CAPIVARI.kmz', url: './cpfl_paulista/CAPIVARI.kmz' },
    { name: 'CONGONHAS.kmz', url: './cpfl_paulista/CONGONHAS.kmz' },
    { name: 'COSMOPOLIS.kmz', url: './cpfl_paulista/COSMOPOLIS.kmz' },
    { name: 'CRAVINHOS.kmz', url: './cpfl_paulista/CRAVINHOS.kmz' },
    { name: 'DESCALVADO.kmz', url: './cpfl_paulista/DESCALVADO.kmz' },
    { name: 'DOIS CORREGOS.kmz', url: './cpfl_paulista/DOIS CORREGOS.kmz' },
    { name: 'DOURADO.kmz', url: './cpfl_paulista/DOURADO.kmz' },
    { name: 'DUARTINA.kmz', url: './cpfl_paulista/DUARTINA.kmz' },
    { name: 'ESPIRITO SANTO DO PINHAL.kmz', url: './cpfl_paulista/ESPIRITO SANTO DO PINHAL.kmz' },
    { name: 'FRANCA.kmz', url: './cpfl_paulista/FRANCA.kmz' },
    { name: 'GARCA.kmz', url: './cpfl_paulista/GARCA.kmz' },
    { name: 'GAVIAO PEIXOTO.kmz', url: './cpfl_paulista/GAVIAO PEIXOTO.kmz' },
    { name: 'GETULINA.kmz', url: './cpfl_paulista/GETULINA.kmz' },
    { name: 'GUAIRA.kmz', url: './cpfl_paulista/GUAIRA.kmz' },
    { name: 'GUANABARA.kmz', url: './cpfl_paulista/GUANABARA.kmz' },
    { name: 'GUARARAPES.kmz', url: './cpfl_paulista/GUARARAPES.kmz' },
    { name: 'GUARIBA.kmz', url: './cpfl_paulista/GUARIBA.kmz' },
    { name: 'HIPODROMO.kmz', url: './cpfl_paulista/HIPODROMO.kmz' },
    { name: 'HORTOLANDIA.kmz', url: './cpfl_paulista/HORTOLANDIA.kmz' },
    { name: 'IACANGA.kmz', url: './cpfl_paulista/IACANGA.kmz' },
    { name: 'IBIRA.kmz', url: './cpfl_paulista/IBIRA.kmz' },
    { name: 'IBITINGA.kmz', url: './cpfl_paulista/IBITINGA.kmz' },
    { name: 'IGARAPAVA.kmz', url: './cpfl_paulista/IGARAPAVA.kmz' },
    { name: 'IPUA.kmz', url: './cpfl_paulista/IPUA.kmz' },
    { name: 'ITAPIRA.kmz', url: './cpfl_paulista/ITAPIRA.kmz' },
    { name: 'ITAPOLIS.kmz', url: './cpfl_paulista/ITAPOLIS.kmz' },
    { name: 'ITATIBA.kmz', url: './cpfl_paulista/ITATIBA.kmz' },
    { name: 'ITUVERAVA.kmz', url: './cpfl_paulista/ITUVERAVA.kmz' },
    { name: 'JABOTICABAL.kmz', url: './cpfl_paulista/JABOTICABAL.kmz' },
    { name: 'JARDINOPOLIS.kmz', url: './cpfl_paulista/JARDINOPOLIS.kmz' },
    { name: 'JAU.kmz', url: './cpfl_paulista/JAU.kmz' },
    { name: 'JOSE BONIFACIO.kmz', url: './cpfl_paulista/JOSE BONIFACIO.kmz' },
    { name: 'LENCOIS PAULISTA.kmz', url: './cpfl_paulista/LENCOIS PAULISTA.kmz' },
    { name: 'LINS.kmz', url: './cpfl_paulista/LINS.kmz' },
    { name: 'MARILIA.kmz', url: './cpfl_paulista/MARILIA.kmz' },
    { name: 'MATAO.kmz', url: './cpfl_paulista/MATAO.kmz' },
    { name: 'METROPOLITANA.kmz', url: './cpfl_paulista/METROPOLITANA.kmz' },
    { name: 'MIGUELOPOLIS.kmz', url: './cpfl_paulista/MIGUELOPOLIS.kmz' },
    { name: 'MIRASSOL.kmz', url: './cpfl_paulista/MIRASSOL.kmz' },
    { name: 'MONTE ALTO.kmz', url: './cpfl_paulista/MONTE ALTO.kmz' },
    { name: 'MONTE APRAZIVEL.kmz', url: './cpfl_paulista/MONTE APRAZIVEL.kmz' },
    { name: 'MONTE MOR.kmz', url: './cpfl_paulista/MONTE MOR.kmz' },
    { name: 'MORRO AGUDO.kmz', url: './cpfl_paulista/MORRO AGUDO.kmz' },
    { name: 'MORRO DO CIPO.kmz', url: './cpfl_paulista/MORRO DO CIPO.kmz' },
    { name: 'NOVA GRANADA.kmz', url: './cpfl_paulista/NOVA GRANADA.kmz' },
    { name: 'OLIMPIA.kmz', url: './cpfl_paulista/OLIMPIA.kmz' },
    { name: 'ORLANDIA.kmz', url: './cpfl_paulista/ORLANDIA.kmz' },
    { name: 'PARAISO.kmz', url: './cpfl_paulista/PARAISO.kmz' },
    { name: 'PARDINHO.kmz', url: './cpfl_paulista/PARDINHO.kmz' },
    { name: 'PAULINIA.kmz', url: './cpfl_paulista/PAULINIA.kmz' },
    { name: 'PEDERNEIRAS.kmz', url: './cpfl_paulista/PEDERNEIRAS.kmz' },
    { name: 'PEDREGULHO.kmz', url: './cpfl_paulista/PEDREGULHO.kmz' },
    { name: 'PENAPOLIS.kmz', url: './cpfl_paulista/PENAPOLIS.kmz' },
    { name: 'PIACATU.kmz', url: './cpfl_paulista/PIACATU.kmz' },
    { name: 'PIRACICABA SANTA CECILIA.kmz', url: './cpfl_paulista/PIRACICABA SANTA CECILIA.kmz' },
    { name: 'PIRACICABA SANTA TEREZINHA.kmz', url: './cpfl_paulista/PIRACICABA SANTA TEREZINHA.kmz' },
    { name: 'PIRACICABA.kmz', url: './cpfl_paulista/PIRACICABA.kmz' },
    { name: 'PIRAJUI - EA.kmz', url: './cpfl_paulista/PIRAJUI - EA.kmz' },
    { name: 'PIRANGI.kmz', url: './cpfl_paulista/PIRANGI.kmz' },
    { name: 'PITANGUEIRAS.kmz', url: './cpfl_paulista/PITANGUEIRAS.kmz' },
    { name: 'POMPEIA.kmz', url: './cpfl_paulista/POMPEIA.kmz' },
    { name: 'PRESIDENTE ALVES.kmz', url: './cpfl_paulista/PRESIDENTE ALVES.kmz' },
    { name: 'PROMISSAO.kmz', url: './cpfl_paulista/PROMISSAO.kmz' },
    { name: 'RESTINGA.kmz', url: './cpfl_paulista/RESTINGA.kmz' },
    { name: 'RIBEIRAO PRETO NORTE.kmz', url: './cpfl_paulista/RIBEIRAO PRETO NORTE.kmz' },
    { name: 'RIBEIRAO PRETO SUL.kmz', url: './cpfl_paulista/RIBEIRAO PRETO SUL.kmz' },
    { name: 'RINCAO.kmz', url: './cpfl_paulista/RINCAO.kmz' },
    { name: 'SANTA ADELIA.kmz', url: './cpfl_paulista/SANTA ADELIA.kmz' },
    { name: 'SANTA BARBARA DOESTE.kmz', url: './cpfl_paulista/SANTA BARBARA DOESTE.kmz' },
    { name: 'SANTA ROSA DE VITERBO.kmz', url: './cpfl_paulista/SANTA ROSA DE VITERBO.kmz' },
    { name: 'SAO CARLOS.kmz', url: './cpfl_paulista/SAO CARLOS.kmz' },
    { name: 'SAO JOAQUIM DA BARRA.kmz', url: './cpfl_paulista/SAO JOAQUIM DA BARRA.kmz' },
    { name: 'SAO JOSE RIO PRETO.kmz', url: './cpfl_paulista/SAO JOSE RIO PRETO.kmz' },
    { name: 'SAO MANUEL.kmz', url: './cpfl_paulista/SAO MANUEL.kmz' },
    { name: 'SAO PEDRO.kmz', url: './cpfl_paulista/SAO PEDRO.kmz' },
    { name: 'SAO SIMAO.kmz', url: './cpfl_paulista/SAO SIMAO.kmz' },
    { name: 'SERRA NEGRA.kmz', url: './cpfl_paulista/SERRA NEGRA.kmz' },
    { name: 'SERRANA.kmz', url: './cpfl_paulista/SERRANA.kmz' },
    { name: 'SERTAOZINHO.kmz', url: './cpfl_paulista/SERTAOZINHO.kmz' },
    { name: 'SOCORRO.kmz', url: './cpfl_paulista/SOCORRO.kmz' },
    { name: 'SUMARE.kmz', url: './cpfl_paulista/SUMARE.kmz' },
    { name: 'TANABI.kmz', url: './cpfl_paulista/TANABI.kmz' },
    { name: 'TAQUARITINGA.kmz', url: './cpfl_paulista/TAQUARITINGA.kmz' },
    { name: 'UIRAPURU.kmz', url: './cpfl_paulista/UIRAPURU.kmz' },
    { name: 'VALINHOS.kmz', url: './cpfl_paulista/VALINHOS.kmz' },
    { name: 'VIRADOURO.kmz', url: './cpfl_paulista/VIRADOURO.kmz' },
];