const predefinedFiles = [
    { name: 'AGUDO.kmz', url: './cpfl_rge/AGUDO.kmz' },
    { name: 'ALEGRETE.kmz', url: './cpfl_rge/ALEGRETE.kmz' },
    { name: 'ANTÔNIO PRADO.kmz', url: './cpfl_rge/ANTÔNIO PRADO.kmz' },
    { name: 'BENTO GONÇALVES.kmz', url: './cpfl_rge/BENTO GONÇALVES.kmz' },
    { name: 'CACHOEIRA.kmz', url: './cpfl_rge/CACHOEIRA.kmz' },
    { name: 'CACHOEIRINHA.kmz', url: './cpfl_rge/CACHOEIRINHA.kmz' },
    { name: 'CAMPO BOM.kmz', url: './cpfl_rge/CAMPO BOM.kmz' },
    { name: 'CAMPO NOVO.kmz', url: './cpfl_rge/CAMPO NOVO.kmz' },
    { name: 'CANELA.kmz', url: './cpfl_rge/CANELA.kmz' },
    { name: 'CANOAS.kmz', url: './cpfl_rge/CANOAS.kmz' },
    { name: 'CARLOS BARBOSA.kmz', url: './cpfl_rge/CARLOS BARBOSA.kmz' },
    { name: 'CAXIAS DO SUL.kmz', url: './cpfl_rge/CAXIAS DO SUL.kmz' },
    { name: 'CAÇAPAVA.kmz', url: './cpfl_rge/CAÇAPAVA.kmz' },
    { name: 'CERRO LARGO.kmz', url: './cpfl_rge/CERRO LARGO.kmz' },
    { name: 'CIDADE INDUSTRIAL.kmz', url: './cpfl_rge/CIDADE INDUSTRIAL.kmz' },
    { name: 'CONSTANTINA.kmz', url: './cpfl_rge/CONSTANTINA.kmz' },
    { name: 'CRUZ ALTA.kmz', url: './cpfl_rge/CRUZ ALTA.kmz' },
    { name: 'CRUZEIRO.kmz', url: './cpfl_rge/CRUZEIRO.kmz' },
    { name: 'DOIS IRMÃOS.kmz', url: './cpfl_rge/DOIS IRMÃOS.kmz' },
    { name: 'ENCANTADO.kmz', url: './cpfl_rge/ENCANTADO.kmz' },
    { name: 'ENTRE RIOS DO SUL.kmz', url: './cpfl_rge/ENTRE RIOS DO SUL.kmz' },
    { name: 'ERECHIM.kmz', url: './cpfl_rge/ERECHIM.kmz' },
    { name: 'ESTANCIA VELHA.kmz', url: './cpfl_rge/ESTANCIA VELHA.kmz' },
    { name: 'ESTEIO.kmz', url: './cpfl_rge/ESTEIO.kmz' },
    { name: 'ESTRELA.kmz', url: './cpfl_rge/ESTRELA.kmz' },
    { name: 'FARROUPILHA.kmz', url: './cpfl_rge/FARROUPILHA.kmz' },
    { name: 'FLORES DA CUNHA.kmz', url: './cpfl_rge/FLORES DA CUNHA.kmz' },
    { name: 'FREDERICO WESTPHALEN.kmz', url: './cpfl_rge/FREDERICO WESTPHALEN.kmz' },
    { name: 'GAURAMA.kmz', url: './cpfl_rge/GAURAMA.kmz' },
    { name: 'GETULIO VARGAS.kmz', url: './cpfl_rge/GETULIO VARGAS.kmz' },
    { name: 'GRAMADO.kmz', url: './cpfl_rge/GRAMADO.kmz' },
    { name: 'GRAVATAÍ.kmz', url: './cpfl_rge/GRAVATAÍ.kmz' },
    { name: 'GUAPORÉ.kmz', url: './cpfl_rge/GUAPORÉ.kmz' },
    { name: 'HORIZONTINA.kmz', url: './cpfl_rge/HORIZONTINA.kmz' },
    { name: 'IBIRUBÁ.kmz', url: './cpfl_rge/IBIRUBÁ.kmz' },
    { name: 'ITAQUI.kmz', url: './cpfl_rge/ITAQUI.kmz' },
    { name: 'LAGOA VERMELHA.kmz', url: './cpfl_rge/LAGOA VERMELHA.kmz' },
    { name: 'LAJEADO.kmz', url: './cpfl_rge/LAJEADO.kmz' },
    { name: 'LIVRAMENTO.kmz', url: './cpfl_rge/LIVRAMENTO.kmz' },
    { name: 'MARAU.kmz', url: './cpfl_rge/MARAU.kmz' },
    { name: 'MONTENEGRO.kmz', url: './cpfl_rge/MONTENEGRO.kmz' },
    { name: 'NOVA PETRÓPOLIS.kmz', url: './cpfl_rge/NOVA PETRÓPOLIS.kmz' },
    { name: 'NOVA PRATA.kmz', url: './cpfl_rge/NOVA PRATA.kmz' },
    { name: 'NOVO HAMBURGO.kmz', url: './cpfl_rge/NOVO HAMBURGO.kmz' },
    { name: 'PAIM FILHO.kmz', url: './cpfl_rge/PAIM FILHO.kmz' },
    { name: 'PALMEIRA DAS MISSÕES.kmz', url: './cpfl_rge/PALMEIRA DAS MISSÕES.kmz' },
    { name: 'PAROBÉ.kmz', url: './cpfl_rge/PAROBÉ.kmz' },
    { name: 'PASSO FUNDO.kmz', url: './cpfl_rge/PASSO FUNDO.kmz' },
    { name: 'PORTÃO.kmz', url: './cpfl_rge/PORTÃO.kmz' },
    { name: 'RIO PARDO.kmz', url: './cpfl_rge/RIO PARDO.kmz' },
    { name: 'ROSARIO.kmz', url: './cpfl_rge/ROSARIO.kmz' },
    { name: 'SANTA CRUZ.kmz', url: './cpfl_rge/SANTA CRUZ.kmz' },
    { name: 'SANTA MARIA.kmz', url: './cpfl_rge/SANTA MARIA.kmz' },
    { name: 'SANTA MARTA.kmz', url: './cpfl_rge/SANTA MARTA.kmz' },
    { name: 'SANTIAGO.kmz', url: './cpfl_rge/SANTIAGO.kmz' },
    { name: 'SANTO CRISTO.kmz', url: './cpfl_rge/SANTO CRISTO.kmz' },
    { name: 'SANTO ÂNGELO.kmz', url: './cpfl_rge/SANTO ÂNGELO.kmz' },
    { name: 'SAPIRANGA.kmz', url: './cpfl_rge/SAPIRANGA.kmz' },
    { name: 'SAPUCAIA.kmz', url: './cpfl_rge/SAPUCAIA.kmz' },
    { name: 'SARANDI.kmz', url: './cpfl_rge/SARANDI.kmz' },
    { name: 'SOLEDADE.kmz', url: './cpfl_rge/SOLEDADE.kmz' },
    { name: 'SÃO BORJA.kmz', url: './cpfl_rge/SÃO BORJA.kmz' },
    { name: 'SÃO GABRIEL.kmz', url: './cpfl_rge/SÃO GABRIEL.kmz' },
    { name: 'SÃO LEOPOLDO.kmz', url: './cpfl_rge/SÃO LEOPOLDO.kmz' },
    { name: 'SÃO LUIZ GONZAGA.kmz', url: './cpfl_rge/SÃO LUIZ GONZAGA.kmz' },
    { name: 'SÃO MARCOS.kmz', url: './cpfl_rge/SÃO MARCOS.kmz' },
    { name: 'SÃO PEDRO.kmz', url: './cpfl_rge/SÃO PEDRO.kmz' },
    { name: 'SÃO SEBASTIÃO DO CAÍ.kmz', url: './cpfl_rge/SÃO SEBASTIÃO DO CAÍ.kmz' },
    { name: 'TAQUARA.kmz', url: './cpfl_rge/TAQUARA.kmz' },
    { name: 'TRÊS COROAS.kmz', url: './cpfl_rge/TRÊS COROAS.kmz' },
    { name: 'TRÊS PASSOS.kmz', url: './cpfl_rge/TRÊS PASSOS.kmz' },
    { name: 'TUPANCIRETÃ.kmz', url: './cpfl_rge/TUPANCIRETÃ.kmz' },
    { name: 'URUGUAIANA.kmz', url: './cpfl_rge/URUGUAIANA.kmz' },
    { name: 'VACARIA.kmz', url: './cpfl_rge/VACARIA.kmz' },
    { name: 'VENÂNCIO AIRES.kmz', url: './cpfl_rge/VENÂNCIO AIRES.kmz' },
    { name: 'VERANÓPOLIS.kmz', url: './cpfl_rge/VERANÓPOLIS.kmz' },
];