const predefinedFiles = [
    { name: 'AGUAS DE LINDOIA.kmz', url: './cpfl_paulista/AGUAS DE LINDOIA.kmz' },
    { name: 'AGUDOS.kmz', url: './cpfl_paulista/AGUDOS.kmz' },
    { name: 'ALTINOPOLIS.kmz', url: './cpfl_paulista/ALTINOPOLIS.kmz' },
    { name: 'AMERICANA.kmz', url: './cpfl_paulista/AMERICANA.kmz' },
    { name: 'AMPARO.kmz', url: './cpfl_paulista/AMPARO.kmz' },
    { name: 'ARACATUBA.kmz', url: './cpfl_paulista/ARACATUBA.kmz' },
    { name: 'ARARAQUARA.kmz', url: './cpfl_paulista/ARARAQUARA.kmz' },
    { name: 'BARIRI.kmz', url: './cpfl_paulista/BARIRI.kmz' },
    { name: 'BARRA BONITA.kmz', url: './cpfl_paulista/BARRA BONITA.kmz' },
    { name: 'BARRETOS.kmz', url: './cpfl_paulista/BARRETOS.kmz' },
    { name: 'BATATAIS.kmz', url: './cpfl_paulista/BATATAIS.kmz' },
    { name: 'BAURU.kmz', url: './cpfl_paulista/BAURU.kmz' },
    { name: 'BEBEDOURO.kmz', url: './cpfl_paulista/BEBEDOURO.kmz' },
    { name: 'BIRIGUI.kmz', url: './cpfl_paulista/BIRIGUI.kmz' },
    { name: 'BOA ESPERANCA DO SUL.kmz', url: './cpfl_paulista/BOA ESPERANCA DO SUL.kmz' },
    { name: 'BOTUCATU.kmz', url: './cpfl_paulista/BOTUCATU.kmz' },
    { name: 'BRAUNA.kmz', url: './cpfl_paulista/BRAUNA.kmz' },
    { name: 'BROTAS.kmz', url: './cpfl_paulista/BROTAS.kmz' },
    { name: 'CAFELANDIA.kmz', url: './cpfl_paulista/CAFELANDIA.kmz' },
    { name: 'CAJOBI.kmz', url: './cpfl_paulista/CAJOBI.kmz' },
    { name: 'CAJURU.kmz', url: './cpfl_paulista/CAJURU.kmz' },
    { name: 'CAMPINAS BARAO GERALDO.kmz', url: './cpfl_paulista/CAMPINAS BARAO GERALDO.kmz' },
    { name: 'CAMPINAS CAMPO GRANDE.kmz', url: './cpfl_paulista/CAMPINAS CAMPO GRANDE.kmz' },
    { name: 'CAMPINAS CENTRO.kmz', url: './cpfl_paulista/CAMPINAS CENTRO.kmz' },
    { name: 'CAMPINAS SOUZAS.kmz', url: './cpfl_paulista/CAMPINAS SOUZAS.kmz' },
    { name: 'CAMPINAS TREVO.kmz', url: './cpfl_paulista/CAMPINAS TREVO.kmz' },
    { name: 'CAPIVARI.kmz', url: './cpfl_paulista/CAPIVARI.kmz' },
    { name: 'CONGONHAS.kmz', url: './cpfl_paulista/CONGONHAS.kmz' },
    { name: 'COSMOPOLIS.kmz', url: './cpfl_paulista/COSMOPOLIS.kmz' },
    { name: 'CRAVINHOS.kmz', url: './cpfl_paulista/CRAVINHOS.kmz' },
    { name: 'DESCALVADO.kmz', url: './cpfl_paulista/DESCALVADO.kmz' },
    { name: 'DOIS CORREGOS.kmz', url: './cpfl_paulista/DOIS CORREGOS.kmz' },
    { name: 'DOURADO.kmz', url: './cpfl_paulista/DOURADO.kmz' },
    { name: 'DUARTINA.kmz', url: './cpfl_paulista/DUARTINA.kmz' },
    { name: 'ESPIRITO SANTO DO PINHAL.kmz', url: './cpfl_paulista/ESPIRITO SANTO DO PINHAL.kmz' },
    { name: 'FRANCA.kmz', url: './cpfl_paulista/FRANCA.kmz' },
    { name: 'GARCA.kmz', url: './cpfl_paulista/GARCA.kmz' },
    { name: 'GAVIAO PEIXOTO.kmz', url: './cpfl_paulista/GAVIAO PEIXOTO.kmz' },
    { name: 'GETULINA.kmz', url: './cpfl_paulista/GETULINA.kmz' },
    { name: 'GUAIRA.kmz', url: './cpfl_paulista/GUAIRA.kmz' },
    { name: 'GUANABARA.kmz', url: './cpfl_paulista/GUANABARA.kmz' },
    { name: 'GUARARAPES.kmz', url: './cpfl_paulista/GUARARAPES.kmz' },
    { name: 'GUARIBA.kmz', url: './cpfl_paulista/GUARIBA.kmz' },
    { name: 'HIPODROMO.kmz', url: './cpfl_paulista/HIPODROMO.kmz' },
    { name: 'HORTOLANDIA.kmz', url: './cpfl_paulista/HORTOLANDIA.kmz' },
    { name: 'IACANGA.kmz', url: './cpfl_paulista/IACANGA.kmz' },
    { name: 'IBIRA.kmz', url: './cpfl_paulista/IBIRA.kmz' },
    { name: 'IBITINGA.kmz', url: './cpfl_paulista/IBITINGA.kmz' },
    { name: 'IGARAPAVA.kmz', url: './cpfl_paulista/IGARAPAVA.kmz' },
    { name: 'IPUA.kmz', url: './cpfl_paulista/IPUA.kmz' },
    { name: 'ITAPIRA.kmz', url: './cpfl_paulista/ITAPIRA.kmz' },
    { name: 'ITAPOLIS.kmz', url: './cpfl_paulista/ITAPOLIS.kmz' },
    { name: 'ITATIBA.kmz', url: './cpfl_paulista/ITATIBA.kmz' },
    { name: 'ITUVERAVA.kmz', url: './cpfl_paulista/ITUVERAVA.kmz' },
    { name: 'JABOTICABAL.kmz', url: './cpfl_paulista/JABOTICABAL.kmz' },
    { name: 'JARDINOPOLIS.kmz', url: './cpfl_paulista/JARDINOPOLIS.kmz' },
    { name: 'JAU.kmz', url: './cpfl_paulista/JAU.kmz' },
    { name: 'JOSE BONIFACIO.kmz', url: './cpfl_paulista/JOSE BONIFACIO.kmz' },
    { name: 'LENCOIS PAULISTA.kmz', url: './cpfl_paulista/LENCOIS PAULISTA.kmz' },
    { name: 'LINS.kmz', url: './cpfl_paulista/LINS.kmz' },
    { name: 'MARILIA.kmz', url: './cpfl_paulista/MARILIA.kmz' },
    { name: 'MATAO.kmz', url: './cpfl_paulista/MATAO.kmz' },
    { name: 'METROPOLITANA.kmz', url: './cpfl_paulista/METROPOLITANA.kmz' },
    { name: 'MIGUELOPOLIS.kmz', url: './cpfl_paulista/MIGUELOPOLIS.kmz' },
    { name: 'MIRASSOL.kmz', url: './cpfl_paulista/MIRASSOL.kmz' },
    { name: 'MONTE ALTO.kmz', url: './cpfl_paulista/MONTE ALTO.kmz' },
    { name: 'MONTE APRAZIVEL.kmz', url: './cpfl_paulista/MONTE APRAZIVEL.kmz' },
    { name: 'MONTE MOR.kmz', url: './cpfl_paulista/MONTE MOR.kmz' },
    { name: 'MORRO AGUDO.kmz', url: './cpfl_paulista/MORRO AGUDO.kmz' },
    { name: 'MORRO DO CIPO.kmz', url: './cpfl_paulista/MORRO DO CIPO.kmz' },
    { name: 'NOVA GRANADA.kmz', url: './cpfl_paulista/NOVA GRANADA.kmz' },
    { name: 'OLIMPIA.kmz', url: './cpfl_paulista/OLIMPIA.kmz' },
    { name: 'ORLANDIA.kmz', url: './cpfl_paulista/ORLANDIA.kmz' },
    { name: 'PARAISO.kmz', url: './cpfl_paulista/PARAISO.kmz' },
    { name: 'PARDINHO.kmz', url: './cpfl_paulista/PARDINHO.kmz' },
    { name: 'PAULINIA.kmz', url: './cpfl_paulista/PAULINIA.kmz' },
    { name: 'PEDERNEIRAS.kmz', url: './cpfl_paulista/PEDERNEIRAS.kmz' },
    { name: 'PEDREGULHO.kmz', url: './cpfl_paulista/PEDREGULHO.kmz' },
    { name: 'PENAPOLIS.kmz', url: './cpfl_paulista/PENAPOLIS.kmz' },
    { name: 'PIACATU.kmz', url: './cpfl_paulista/PIACATU.kmz' },
    { name: 'PIRACICABA SANTA CECILIA.kmz', url: './cpfl_paulista/PIRACICABA SANTA CECILIA.kmz' },
    { name: 'PIRACICABA SANTA TEREZINHA.kmz', url: './cpfl_paulista/PIRACICABA SANTA TEREZINHA.kmz' },
    { name: 'PIRACICABA.kmz', url: './cpfl_paulista/PIRACICABA.kmz' },
    { name: 'PIRAJUI - EA.kmz', url: './cpfl_paulista/PIRAJUI - EA.kmz' },
    { name: 'PIRANGI.kmz', url: './cpfl_paulista/PIRANGI.kmz' },
    { name: 'PITANGUEIRAS.kmz', url: './cpfl_paulista/PITANGUEIRAS.kmz' },
    { name: 'POMPEIA.kmz', url: './cpfl_paulista/POMPEIA.kmz' },
    { name: 'PRESIDENTE ALVES.kmz', url: './cpfl_paulista/PRESIDENTE ALVES.kmz' },
    { name: 'PROMISSAO.kmz', url: './cpfl_paulista/PROMISSAO.kmz' },
    { name: 'RESTINGA.kmz', url: './cpfl_paulista/RESTINGA.kmz' },
    { name: 'RIBEIRAO PRETO NORTE.kmz', url: './cpfl_paulista/RIBEIRAO PRETO NORTE.kmz' },
    { name: 'RIBEIRAO PRETO SUL.kmz', url: './cpfl_paulista/RIBEIRAO PRETO SUL.kmz' },
    { name: 'RINCAO.kmz', url: './cpfl_paulista/RINCAO.kmz' },
    { name: 'SANTA ADELIA.kmz', url: './cpfl_paulista/SANTA ADELIA.kmz' },
    { name: 'SANTA BARBARA DOESTE.kmz', url: './cpfl_paulista/SANTA BARBARA DOESTE.kmz' },
    { name: 'SANTA ROSA DE VITERBO.kmz', url: './cpfl_paulista/SANTA ROSA DE VITERBO.kmz' },
    { name: 'SAO CARLOS.kmz', url: './cpfl_paulista/SAO CARLOS.kmz' },
    { name: 'SAO JOAQUIM DA BARRA.kmz', url: './cpfl_paulista/SAO JOAQUIM DA BARRA.kmz' },
    { name: 'SAO JOSE RIO PRETO.kmz', url: './cpfl_paulista/SAO JOSE RIO PRETO.kmz' },
    { name: 'SAO MANUEL.kmz', url: './cpfl_paulista/SAO MANUEL.kmz' },
    { name: 'SAO PEDRO.kmz', url: './cpfl_paulista/SAO PEDRO.kmz' },
    { name: 'SAO SIMAO.kmz', url: './cpfl_paulista/SAO SIMAO.kmz' },
    { name: 'SERRA NEGRA.kmz', url: './cpfl_paulista/SERRA NEGRA.kmz' },
    { name: 'SERRANA.kmz', url: './cpfl_paulista/SERRANA.kmz' },
    { name: 'SERTAOZINHO.kmz', url: './cpfl_paulista/SERTAOZINHO.kmz' },
    { name: 'SOCORRO.kmz', url: './cpfl_paulista/SOCORRO.kmz' },
    { name: 'SUMARE.kmz', url: './cpfl_paulista/SUMARE.kmz' },
    { name: 'TANABI.kmz', url: './cpfl_paulista/TANABI.kmz' },
    { name: 'TAQUARITINGA.kmz', url: './cpfl_paulista/TAQUARITINGA.kmz' },
    { name: 'UIRAPURU.kmz', url: './cpfl_paulista/UIRAPURU.kmz' },
    { name: 'VALINHOS.kmz', url: './cpfl_paulista/VALINHOS.kmz' },
    { name: 'VIRADOURO.kmz', url: './cpfl_paulista/VIRADOURO.kmz' },
    { name: 'BOITUVA.kmz', url: './cpfl_piratininga/BOITUVA.kmz' },
    { name: 'CAMPO LIMPO.kmz', url: './cpfl_piratininga/CAMPO LIMPO.kmz' },
    { name: 'CAPELA DO ALTO.kmz', url: './cpfl_piratininga/CAPELA DO ALTO.kmz' },
    { name: 'CUBATAO.kmz', url: './cpfl_piratininga/CUBATAO.kmz' },
    { name: 'IBIUNA.kmz', url: './cpfl_piratininga/IBIUNA.kmz' },
    { name: 'INDAIATUBA.kmz', url: './cpfl_piratininga/INDAIATUBA.kmz' },
    { name: 'ITU.kmz', url: './cpfl_piratininga/ITU.kmz' },
    { name: 'JUNDIAI.kmz', url: './cpfl_piratininga/JUNDIAI.kmz' },
    { name: 'LOUVEIRA.kmz', url: './cpfl_piratininga/LOUVEIRA.kmz' },
    { name: 'MAIRINQUE.kmz', url: './cpfl_piratininga/MAIRINQUE.kmz' },
    { name: 'PORTO FELIZ.kmz', url: './cpfl_piratininga/PORTO FELIZ.kmz' },
    { name: 'PRAIA GRANDE.kmz', url: './cpfl_piratininga/PRAIA GRANDE.kmz' },
    { name: 'SALTO DE PIRAPORA.kmz', url: './cpfl_piratininga/SALTO DE PIRAPORA.kmz' },
    { name: 'SALTO.kmz', url: './cpfl_piratininga/SALTO.kmz' },
    { name: 'SANTOS.kmz', url: './cpfl_piratininga/SANTOS.kmz' },
    { name: 'SAO ROQUE.kmz', url: './cpfl_piratininga/SAO ROQUE.kmz' },
    { name: 'SAO VICENTE.kmz', url: './cpfl_piratininga/SAO VICENTE.kmz' },
    { name: 'SOROCABA.kmz', url: './cpfl_piratininga/SOROCABA.kmz' },
    { name: 'VARZEA PAULISTA.kmz', url: './cpfl_piratininga/VARZEA PAULISTA.kmz' },
    { name: 'VICENTE DE CARVALHO.kmz', url: './cpfl_piratininga/VICENTE DE CARVALHO.kmz' },
    { name: 'VINHEDO.kmz', url: './cpfl_piratininga/VINHEDO.kmz' },
    { name: 'VOTORANTIM.kmz', url: './cpfl_piratininga/VOTORANTIM.kmz' },
    { name: 'AGUDO.kmz', url: './cpfl_rge/AGUDO.kmz' },
    { name: 'ALEGRETE.kmz', url: './cpfl_rge/ALEGRETE.kmz' },
    { name: 'ANTÔNIO PRADO.kmz', url: './cpfl_rge/ANTÔNIO PRADO.kmz' },
    { name: 'BENTO GONÇALVES.kmz', url: './cpfl_rge/BENTO GONÇALVES.kmz' },
    { name: 'CACHOEIRA.kmz', url: './cpfl_rge/CACHOEIRA.kmz' },
    { name: 'CACHOEIRINHA.kmz', url: './cpfl_rge/CACHOEIRINHA.kmz' },
    { name: 'CAMPO BOM.kmz', url: './cpfl_rge/CAMPO BOM.kmz' },
    { name: 'CAMPO NOVO.kmz', url: './cpfl_rge/CAMPO NOVO.kmz' },
    { name: 'CANELA.kmz', url: './cpfl_rge/CANELA.kmz' },
    { name: 'CANOAS.kmz', url: './cpfl_rge/CANOAS.kmz' },
    { name: 'CARLOS BARBOSA.kmz', url: './cpfl_rge/CARLOS BARBOSA.kmz' },
    { name: 'CAXIAS DO SUL.kmz', url: './cpfl_rge/CAXIAS DO SUL.kmz' },
    { name: 'CAÇAPAVA.kmz', url: './cpfl_rge/CAÇAPAVA.kmz' },
    { name: 'CERRO LARGO.kmz', url: './cpfl_rge/CERRO LARGO.kmz' },
    { name: 'CIDADE INDUSTRIAL.kmz', url: './cpfl_rge/CIDADE INDUSTRIAL.kmz' },
    { name: 'CONSTANTINA.kmz', url: './cpfl_rge/CONSTANTINA.kmz' },
    { name: 'CRUZ ALTA.kmz', url: './cpfl_rge/CRUZ ALTA.kmz' },
    { name: 'CRUZEIRO.kmz', url: './cpfl_rge/CRUZEIRO.kmz' },
    { name: 'DOIS IRMÃOS.kmz', url: './cpfl_rge/DOIS IRMÃOS.kmz' },
    { name: 'ENCANTADO.kmz', url: './cpfl_rge/ENCANTADO.kmz' },
    { name: 'ENTRE RIOS DO SUL.kmz', url: './cpfl_rge/ENTRE RIOS DO SUL.kmz' },
    { name: 'ERECHIM.kmz', url: './cpfl_rge/ERECHIM.kmz' },
    { name: 'ESTANCIA VELHA.kmz', url: './cpfl_rge/ESTANCIA VELHA.kmz' },
    { name: 'ESTEIO.kmz', url: './cpfl_rge/ESTEIO.kmz' },
    { name: 'ESTRELA.kmz', url: './cpfl_rge/ESTRELA.kmz' },
    { name: 'FARROUPILHA.kmz', url: './cpfl_rge/FARROUPILHA.kmz' },
    { name: 'FLORES DA CUNHA.kmz', url: './cpfl_rge/FLORES DA CUNHA.kmz' },
    { name: 'FREDERICO WESTPHALEN.kmz', url: './cpfl_rge/FREDERICO WESTPHALEN.kmz' },
    { name: 'GAURAMA.kmz', url: './cpfl_rge/GAURAMA.kmz' },
    { name: 'GETULIO VARGAS.kmz', url: './cpfl_rge/GETULIO VARGAS.kmz' },
    { name: 'GRAMADO.kmz', url: './cpfl_rge/GRAMADO.kmz' },
    { name: 'GRAVATAÍ.kmz', url: './cpfl_rge/GRAVATAÍ.kmz' },
    { name: 'GUAPORÉ.kmz', url: './cpfl_rge/GUAPORÉ.kmz' },
    { name: 'HORIZONTINA.kmz', url: './cpfl_rge/HORIZONTINA.kmz' },
    { name: 'IBIRUBÁ.kmz', url: './cpfl_rge/IBIRUBÁ.kmz' },
    { name: 'ITAQUI.kmz', url: './cpfl_rge/ITAQUI.kmz' },
    { name: 'LAGOA VERMELHA.kmz', url: './cpfl_rge/LAGOA VERMELHA.kmz' },
    { name: 'LAJEADO.kmz', url: './cpfl_rge/LAJEADO.kmz' },
    { name: 'LIVRAMENTO.kmz', url: './cpfl_rge/LIVRAMENTO.kmz' },
    { name: 'MARAU.kmz', url: './cpfl_rge/MARAU.kmz' },
    { name: 'MONTENEGRO.kmz', url: './cpfl_rge/MONTENEGRO.kmz' },
    { name: 'NOVA PETRÓPOLIS.kmz', url: './cpfl_rge/NOVA PETRÓPOLIS.kmz' },
    { name: 'NOVA PRATA.kmz', url: './cpfl_rge/NOVA PRATA.kmz' },
    { name: 'NOVO HAMBURGO.kmz', url: './cpfl_rge/NOVO HAMBURGO.kmz' },
    { name: 'PAIM FILHO.kmz', url: './cpfl_rge/PAIM FILHO.kmz' },
    { name: 'PALMEIRA DAS MISSÕES.kmz', url: './cpfl_rge/PALMEIRA DAS MISSÕES.kmz' },
    { name: 'PAROBÉ.kmz', url: './cpfl_rge/PAROBÉ.kmz' },
    { name: 'PASSO FUNDO.kmz', url: './cpfl_rge/PASSO FUNDO.kmz' },
    { name: 'PORTÃO.kmz', url: './cpfl_rge/PORTÃO.kmz' },
    { name: 'RIO PARDO.kmz', url: './cpfl_rge/RIO PARDO.kmz' },
    { name: 'ROSARIO.kmz', url: './cpfl_rge/ROSARIO.kmz' },
    { name: 'SANTA CRUZ.kmz', url: './cpfl_rge/SANTA CRUZ.kmz' },
    { name: 'SANTA MARIA.kmz', url: './cpfl_rge/SANTA MARIA.kmz' },
    { name: 'SANTA MARTA.kmz', url: './cpfl_rge/SANTA MARTA.kmz' },
    { name: 'SANTIAGO.kmz', url: './cpfl_rge/SANTIAGO.kmz' },
    { name: 'SANTO CRISTO.kmz', url: './cpfl_rge/SANTO CRISTO.kmz' },
    { name: 'SANTO ÂNGELO.kmz', url: './cpfl_rge/SANTO ÂNGELO.kmz' },
    { name: 'SAPIRANGA.kmz', url: './cpfl_rge/SAPIRANGA.kmz' },
    { name: 'SAPUCAIA.kmz', url: './cpfl_rge/SAPUCAIA.kmz' },
    { name: 'SARANDI.kmz', url: './cpfl_rge/SARANDI.kmz' },
    { name: 'SOLEDADE.kmz', url: './cpfl_rge/SOLEDADE.kmz' },
    { name: 'SÃO BORJA.kmz', url: './cpfl_rge/SÃO BORJA.kmz' },
    { name: 'SÃO GABRIEL.kmz', url: './cpfl_rge/SÃO GABRIEL.kmz' },
    { name: 'SÃO LEOPOLDO.kmz', url: './cpfl_rge/SÃO LEOPOLDO.kmz' },
    { name: 'SÃO LUIZ GONZAGA.kmz', url: './cpfl_rge/SÃO LUIZ GONZAGA.kmz' },
    { name: 'SÃO MARCOS.kmz', url: './cpfl_rge/SÃO MARCOS.kmz' },
    { name: 'SÃO PEDRO.kmz', url: './cpfl_rge/SÃO PEDRO.kmz' },
    { name: 'SÃO SEBASTIÃO DO CAÍ.kmz', url: './cpfl_rge/SÃO SEBASTIÃO DO CAÍ.kmz' },
    { name: 'TAQUARA.kmz', url: './cpfl_rge/TAQUARA.kmz' },
    { name: 'TRÊS COROAS.kmz', url: './cpfl_rge/TRÊS COROAS.kmz' },
    { name: 'TRÊS PASSOS.kmz', url: './cpfl_rge/TRÊS PASSOS.kmz' },
    { name: 'TUPANCIRETÃ.kmz', url: './cpfl_rge/TUPANCIRETÃ.kmz' },
    { name: 'URUGUAIANA.kmz', url: './cpfl_rge/URUGUAIANA.kmz' },
    { name: 'VACARIA.kmz', url: './cpfl_rge/VACARIA.kmz' },
    { name: 'VENÂNCIO AIRES.kmz', url: './cpfl_rge/VENÂNCIO AIRES.kmz' },
    { name: 'VERANÓPOLIS.kmz', url: './cpfl_rge/VERANÓPOLIS.kmz' },
    { name: 'AVARÉ.kmz', url: './cpfl_santacruz/AVARÉ.kmz' },
    { name: 'CACONDE.kmz', url: './cpfl_santacruz/CACONDE.kmz' },
    { name: 'CASA BRANCA.kmz', url: './cpfl_santacruz/CASA BRANCA.kmz' },
    { name: 'CHAVANTES.kmz', url: './cpfl_santacruz/CHAVANTES.kmz' },
    { name: 'ITAPETININGA.kmz', url: './cpfl_santacruz/ITAPETININGA.kmz' },
    { name: 'ITAÍ.kmz', url: './cpfl_santacruz/ITAÍ.kmz' },
    { name: 'JACAREZINHO.kmz', url: './cpfl_santacruz/JACAREZINHO.kmz' },
    { name: 'JAGUARIÚNA.kmz', url: './cpfl_santacruz/JAGUARIÚNA.kmz' },
    { name: 'MOCOCA.kmz', url: './cpfl_santacruz/MOCOCA.kmz' },
    { name: 'MONTE SANTO DE MINAS.kmz', url: './cpfl_santacruz/MONTE SANTO DE MINAS.kmz' },
    { name: 'OURINHOS.kmz', url: './cpfl_santacruz/OURINHOS.kmz' },
    { name: 'PEDREIRA.kmz', url: './cpfl_santacruz/PEDREIRA.kmz' },
    { name: 'PIRAJU.kmz', url: './cpfl_santacruz/PIRAJU.kmz' },
    { name: 'SANTA CRUZ DO RIO PARDO.kmz', url: './cpfl_santacruz/SANTA CRUZ DO RIO PARDO.kmz' },
    { name: 'SÃO JOSÉ DO RIO PARDO.kmz', url: './cpfl_santacruz/SÃO JOSÉ DO RIO PARDO.kmz' },
    { name: 'SÃO PEDRO DO TURVO.kmz', url: './cpfl_santacruz/SÃO PEDRO DO TURVO.kmz' },
    { name: 'TAQUARITUBA.kmz', url: './cpfl_santacruz/TAQUARITUBA.kmz' },
    { name: 'ÁGUAS DE SANTA BÁRBARA.kmz', url: './cpfl_santacruz/ÁGUAS DE SANTA BÁRBARA.kmz' }
];
