# Docs para a ação Azure Web Apps Deploy: https://github.com/Azure/webapps-deploy
# Mais GitHub Actions para Azure: https://github.com/Azure/actions

name: Build and Deploy ASP.Net Core App to Azure Web App - leitorcpfl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout do código fonte
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      # 2. Cache de pacotes NuGet (opcional, mas recomendado para otimizar o tempo de build)
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # 3. Configurar o .NET Core SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      # 4. Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore

      # 5. Compilar a aplicação
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      # 6. Publicar a aplicação
      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output ./publish

      # 7. Fazer upload dos artefatos para o job de deploy
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      # 1. Baixar os artefatos do job de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      # 2. Implantar no Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'leitorcpfl'  # Nome do seu Azure Web App
          package: ./publish        # Caminho para os artefatos publicados
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5cedd9be7e1a468bb0fe866a83253b77 }}  # Segredo contendo o perfil de publicação
